---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow-lineage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow-lineage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.6.1
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
        - name: AIRFLOW__LINEAGE__BACKEND
          value: openlineage.lineage_backend.OpenLineageBackend
        - name: OPENLINEAGE_URL
          value: http://marquez:5000
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: airflow-lineage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow-lineage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.6.1
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
        - name: AIRFLOW__LINEAGE__BACKEND
          value: openlineage.lineage_backend.OpenLineageBackend
        - name: OPENLINEAGE_URL
          value: http://marquez:5000
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: airflow-lineage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marquez
  namespace: airflow-lineage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marquez
  template:
    metadata:
      labels:
        app: marquez
    spec:
      containers:
      - name: marquez
        image: marquezproject/marquez:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow-lineage
spec:
  selector:
    app: airflow-webserver
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: marquez
  namespace: airflow-lineage
spec:
  selector:
    app: marquez
  ports:
  - port: 5000
    targetPort: 5000