apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-sample
spec:
  rayVersion: '2.0.0'
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
  workerGroupSpecs:
    - groupName: gpu-group
      replicas: 4
      rayStartParams:
        num-gpus: '1'
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.0.0-gpu
              resources:
                limits:
                  nvidia.com/gpu: 1